version: '2'

services:
    web-dev:
        image: ${COMPOSE_PROJECT_NAME}-web-dev:${APP_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}-web-dev
        build:
            context: devops/nginx/dev
            args:
                NGINX_VERSION: ${NGINX_VERSION}
        ports:
            - ${NGINX_HOST_PORT}:80
            - ${NGINX_HOST_SSL_PORT}:443
        volumes:
            - ./volumes/nginx/logs:/var/log/nginx/
        volumes_from:
            - php-dev:ro
        depends_on:
            - php-dev
    php-base:
        image: ${COMPOSE_PROJECT_NAME}-php-base:${APP_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}-php-base
        build:
            context: devops/php-fpm/base
            args:
                PHP_VERSION: ${PHP_VERSION}
    php-dev:
        image: ${COMPOSE_PROJECT_NAME}-php-dev:${APP_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}-php-dev
        build:
            context: devops/php-fpm/dev
            args:
                BASE_IMAGE: ${COMPOSE_PROJECT_NAME}-php-base:${APP_VERSION}
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        volumes:
            - ./:/var/www/app/
            - ${HOME}/.gitconfig:/home/www-data/.gitconfig
            - ${HOME}/.git-credentials:/home/www-data/.git-credentials
            - ${HOME}/.ssh:/home/www-data/.ssh
            - composer_cache:/.composer/cache/
        environment:
            COMPOSER_MEMORY_LIMIT: ${COMPOSER_MEMORY_LIMIT}
        depends_on:
            - php-base
    db-dev:
        image: ${COMPOSE_PROJECT_NAME}-db-dev:${APP_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}-db-dev
        build:
            context: devops/mysql/dev
            args:
                MYSQL_VERSION: ${MYSQL_VERSION}
        volumes:
            - dbplex:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_HOST_PORT}:3306
volumes:
    dbplex:
    composer_cache: